default: &default
  store_options:
    max_age: <%= 60.days.to_i %>
    max_size: <%= 64.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  database: cache
  max_age: <%= 365.days.to_i %>
  max_size: <%= 256.megabytes %>
  <<: *default
